services:
  evobot:
    container_name: evobot
    restart: unless-stopped
    image: netvpc/evobot:latest
    networks:
      - internal
    environment:
      - 'DISCORD_TOKEN='
      - 'UID=1001'
      - 'GID=1001'
      - 'EVOBOT_LOCALE=ko'
networks: 
  internal: